name: Build binaries and release

on:
    push:
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Install and Build 🔧
              run: |
                  npm install
                  npm run package
            - name: Upload to Releases
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dist/*
                  tag_name: ${{ env.RELEASE_VERSION }}
